[package]
name = "gravity_cli"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true


[dependencies]
gaptos.workspace = true
clap.workspace = true
hex.workspace = true
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_yaml.workspace = true
serde_json.workspace = true
tracing.workspace = true
bcs.workspace = true
sha3.workspace = true
rand_core = { version = "0.6", features = ["std"] }
k256 = { version = "0.13.0", features = ["ecdsa"] }

